name: "Keygen"
description: "Keygen"
inputs:
  version:
    description: "Version"
    required: true
  master-password:
    description: "Master password"
    required: true
outputs:
  public-key:
    description: "The public key"
    value: ${{ steps.run.outputs.public-key }}
runs:
  using: "composite"
  steps:
    - name: Determine binary
      shell: bash
      run: |
        ARCH =$(uname -m)
        if [ "${{ runner.os }}" == "Linux" ]; then
          FILENAME="$GITHUB_ACTION_PATH/keygen-linux"
        elif [ "${{ runner.os }}" == "Windows" ]; then
          FILENAME="$GITHUB_ACTION_PATH/keygen-windows"
        elif [ "${{ runner.os }}" == "macOS" ]; then
          if ["$ARCH" = "arm64"]; then
            FILENAME="$GITHUB_ACTION_PATH/keygen-macos-arm"
          else
            FILENAME="$GITHUB_ACTION_PATH/keygen-macos-x86"
          fi
        fi
        echo "BINARY_LOCATION=$FILENAME" >> $GITHUB_ENV
    - name: Add executable bit to keygen (may not be necessary...)
      shell: bash
      run: |
        set -euo pipefail
        chmod +x "${{env.BINARY_LOCATION}}"
    - name: Run keygen
      id: run
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        MASTER_PASSWORD: ${{ inputs['master-password'] }}
      run: |
        set -euo pipefail
        PUBLIC_KEY="$(
          printf '%s' "$MASTER_PASSWORD" | "${{BINARY_LOCATION}}" -- "$VERSION"
        )"

        {
          echo 'public-key<<EOF'
          echo "$PUBLIC_KEY"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
