name: "Keygen"
description: "Keygen"
inputs:
  version:
    description: "Version"
    required: true
  master-password:
    description: "Master password"
    required: true
outputs:
  public-key:
    description: "The public key"
    value: ${{ steps.run.outputs.public-key }}
runs:
  using: "composite"
  steps:
    - name: Add executable bit to keygen (may not be necessary...)
      shell: bash
      run: |
        set -euo pipefail
        chmod +x "$GITHUB_WORKSPACE/keygen"
    - name: Run keygen
      id: run
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        MASTER_PASSWORD: ${{ inputs['master-password'] }}
      run: |
        set -euo pipefail
        PUBLIC_KEY="$(
          printf '%s' "$MASTER_PASSWORD" | "$GITHUB_WORKSPACE/keygen" -- "$VERSION"
        )"

        {
          echo 'public-key<<EOF'
          echo "$PUBLIC_KEY"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
