name: Generate Public Key
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to derive the key for"
        required: true
        type: string

jobs:
  keygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run keygen
        id: k
        uses: ./.github/actions/keygen
        with:
          version: ${{ inputs.version }}
          master-password: ${{ secrets.MASTER_PASSWORD }}

      - name: Echo Public Key
        run: |
          printf '%s\n' "${{ steps.k.outputs.public-key }}"
